name: backend Java CD with Gradle

on:
  pull_request:
    types:
      - closed
    branches: [ "develop" ]
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

permissions:
  contents: read
#  checks: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:

    - name: set up Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Give permission for Gradle
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: ls
      run: ls -al /buid/libs
