# Develop 브랜치에 BE코드 머지 시 Build & Uplaod Artifact

name: backend Java CD with Gradle

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "develop" ]
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

permissions:
  contents: read
#  checks: write

jobs:
  build-upload:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:

    - name: set up Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Give permission for Gradle
      run: chmod +x gradlew
      
    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Build with Gradle
      run: ./gradlew bootJar
      
    - name: Upload to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BackendApplicationJar
        path: backend/build/libs/*.jar
        
  deploy:
    needs: build-upload
    runs-on: self-hosted
    env:
      PROPERTY: ${{ secrets.DEV_PROPERTY }}
      DEV_DEPLOY_SCRIPT: ${{ secrets.DEV_DEPLOY_SCRIPT }}
    steps:

      - uses: actions/download-artifact@v3
        with:
          name: BackendApplicationJar
          path: backend/dev/
          
          
      - name: create application-config file
        working-directory: ./backend/dev/
        run: |
          echo "$PROPERTY" > application.yml
      
      - name: deploy to WAS
        working-directory: ./backend/dev/
        run: |
          echo "$DEV_DEPLOY_SCRIPT" > dev-deploy.sh
          ./dev-deploy.sh
      
