name: backend Java CI with Gradle

on:
  pull_request:
    types:
      - closed
    branches: [ "develop" ]
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
